"""Render the reviewed resource catalog into the native reader; no network/game access.

Update docs/mission-targets.json only from verified, versioned component/path facts.
Every target needs Spottable membership. Path names describe the physical object;
main/side objective importance continues to come from the current mission at runtime.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def render():
    catalog = json.loads((ROOT / 'docs/mission-targets.json').read_text(encoding='utf-8'))
    lines = ['-- BEGIN MISSION TARGET CATALOG',
             '-- Generated by tools/generate_mission_targets.py from docs/mission-targets.json.',
             '-- Current Spottable membership + reviewed resource paths; main/side roles are not inferred.',
             'local MISSION_TARGETS = {']
    seen = set()
    for row in catalog['targets']:
        resource, label, key = row['resource'], row['label'], row['name_key']
        assert re.fullmatch('[0-9A-F]{16}', resource) and resource not in seen
        assert 'SpottableComponentData' in row['components']
        assert 'AiEnemyComponentData' not in row['components']
        assert isinstance(key, int) and 0 <= key <= 0xffffffff
        assert label and not any(c in label for c in "'\\\r\n")
        seen.add(resource)
        lines.append(f"    ['{resource}'] = {{'building', '{label}', {key}}},")
    lines += ['}', '-- END MISSION TARGET CATALOG']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    p = ROOT / 'src/ping_events.lua'
    source = p.read_text(encoding='utf-8')
    pattern = r'-- BEGIN MISSION TARGET CATALOG\n.*?\n-- END MISSION TARGET CATALOG'
    block = render()
    if args.check:
        match = re.search(pattern, source, re.S)
        assert match and match.group() == block, 'mission catalog is out of date'
    else:
        if re.search(pattern, source, re.S):
            source, count = re.subn(pattern, lambda _: block, source, flags=re.S)
            assert count == 1
        else:
            source = source.replace('local PING_TARGETS = {', block + '\n\nlocal PING_TARGETS = {', 1)
        p.write_text(source, encoding='utf-8')
    print('Mission target catalog: checked' if args.check else 'Mission target catalog: generated')


if __name__ == '__main__':
    main()
