-- Third-party reference license (etxp HD2-G60-Smart-Targeting):
--[[
MIT License

Copyright (c) 2026 etxp

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]
-- Read-only native ping adapter for Steam build 25480438 only.
-- game.dll SHA256: 2E2C3B7C2500646DADD5F2B4C6E0504DBB7E7896139F64CDDC0D1813C718F51E
-- env.base() must already enforce that supported build; no native calls or writes here.
-- Observed ring/entity layouts (MIT):
-- https://github.com/etxp/HD2-G60-Smart-Targeting/blob/main/src/g60/native_ping.lua
-- https://github.com/etxp/HD2-G60-Smart-Targeting/blob/main/src/g60/native_target_data.lua
-- Player/peer/avatar layouts, same DLL fingerprint:
-- https://github.com/SkyeShade/HD2Runtime/blob/master/runtime/event_world.lua
-- https://github.com/SkyeShade/HD2Runtime/blob/master/domains/event_natives.lua
-- Classification facts: current-build enemy kind intersected with AiEnemyComponentData;
-- HealthComponentData.unit_size: 0 Small, 1 Medium, 2 Large, 3 Massive (2026-09-22).
-- Hostile faction + Spottable membership are required; flying components take priority.
-- https://github.com/Darctor/Helldivers2_RawData/tree/main/Data/entities
-- https://github.com/Darctor/Helldivers2_RawData/blob/main/Data/enums/UnitSize.txt
-- Tactical map pins use replicated actor state, not the HUD ping ring. Current
-- DLL 18B97A0 writes actor+547830 (stride78); 18B3A90 renders those same pins.
-- Objective names: 1255D60 resolves entity -> definition (32EF870,153 x A0),
-- 18B4AEC selects definition+38 or runtime+1050. Importance is runtime+1038,
-- populated from the CURRENT mission by 5D0DF0, never inferred from the name.
-- Local Custom UI confirms enemy material A1919FA085C97B18, ground 4B81B73A36657DC9;
-- Better Map Markers shares map material EA6C3908C95DD015. These asset hashes do NOT
-- prove a numeric ring-kind enum and are never used as one.
-- Special identities: current RawData EncyclopediaEntryComponentData / EntityComponentMap,
-- HD2Runtime SupportWeaponCapabilities and FileDiver actual resource paths.
-- https://github.com/Darctor/Helldivers2_RawData/blob/main/Data/settings/EntityComponentMap.json
-- https://github.com/SkyeShade/HD2Runtime/blob/master/sdk/SupportWeaponCapabilities.json
-- https://github.com/xypwn/filediver/blob/master/hashes/hashes.txt
-- Enum: https://github.com/shalzuth/HelldiversData/blob/master/data/enums/HudMarkerType.json
-- Historical HUD enum is corroborated by current DLL Map21 producer below.
-- Resource pickups are classified separately so the main policy can keep them
-- behind its supplies switch rather than mislabeling them as buildings.
local EXCLUDED_SUPPLIES = {
    ['9D4935FA69B6B41A']=true, ['307E09E7698881BA']=true, ['4932CBF33CD47EF9']=true,
    ['4C63119F69165321']=true, ['5016EE397FDCFB6C']=true, ['64B49B9D8A445266']=true,
    ['700E9500E95541BF']=true, ['79CCFFD281E3F3A9']=true, ['86F3CB87D97942B4']=true,
    ['92BCC263E751BD45']=true, ['97AF34FBF093409C']=true, ['A9936CBE561E8180']=true,
    ['AD972A2E815A49AA']=true, ['B39FCF5C73D5C383']=true, ['B4CA4C5B922F7965']=true,
    ['BD30758426ED2566']=true, ['BEB2A0F09E36BF72']=true, ['D463836441CD0BA7']=true,
    ['E4EEB96023DF6A99']=true,
}
-- BEGIN MISSION TARGET CATALOG
-- Generated by tools/generate_mission_targets.py from docs/mission-targets.json.
-- Current Spottable membership + reviewed resource paths; main/side roles are not inferred.
local MISSION_TARGETS = {
    ['019F988FA225DD1C'] = {'building', '逃生舱', 0},
    ['01A88312C8889D5F'] = {'building', '炮塔控制终端', 0},
    ['051DA4B57216A005'] = {'building', '任务终端', 0},
    ['06D3C4720E642FC1'] = {'building', '虫卵群', 0},
    ['0722B3A72ADE6CB1'] = {'building', 'TCS 主塔', 0},
    ['073270650F859DD0'] = {'building', '装有化学武器的背包', 3054644200},
    ['0801B6B3C5D12EBC'] = {'building', '地面全地形采集钻机', 3023900891},
    ['095686275A113614'] = {'building', '尖啸虫巢穴', 3496786382},
    ['0A12D5A29CDF2D40'] = {'building', '撤离信标', 0},
    ['0DC9084E50C051F3'] = {'building', '铂金条', 2492072473},
    ['0DF874E208040D2F'] = {'building', '虫穴', 3277626454},
    ['0E88F182E83A4275'] = {'building', '任务交互物', 0},
    ['0F1A0189B327C5CB'] = {'building', '超级固态硬盘', 714952129},
    ['10E44156F08786EF'] = {'building', '生物处理器', 0},
    ['1262CD07B196AAC3'] = {'building', '任务交互物', 0},
    ['1312B769F47256D9'] = {'building', 'SEAF 防空导弹阵地', 1563965062},
    ['142637570A721CB9'] = {'building', '轨道炮弹药供给装置', 0},
    ['15031543894C3F3C'] = {'building', 'TCS 孢子喷涌体', 3139947901},
    ['1556FE9780D5D52D'] = {'building', '任务终端', 0},
    ['15E2A2B11BA78C5A'] = {'building', '任务交互物', 0},
    ['162256BD224F6265'] = {'building', '加注站终端', 0},
    ['16D7BA33ED511664'] = {'building', '控制塔终端', 0},
    ['1A3B52A4D3F166F7'] = {'building', '光能者城市巨炮终端', 0},
    ['1B633762874A709A'] = {'building', '首都防御设施', 0},
    ['1C2360811101BCCE'] = {'building', '冷却管道', 0},
    ['1D72EBD1A6916E67'] = {'building', '装配设施曲柄', 0},
    ['22CC0ED4CEB9CB68'] = {'building', '机器人制造厂', 3794527478},
    ['23C85E970FB46685'] = {'building', '战备干扰器', 0},
    ['245F7D8792CD23E5'] = {'building', '军事通信交付点', 0},
    ['24ACA2B4D15D2E2F'] = {'building', '发电机组', 0},
    ['25C5B9818EF934E3'] = {'building', '任务终端', 0},
    ['2670E0047B2EB409'] = {'building', '探测塔', 0},
    ['2778F620A6E414AF'] = {'building', '光能者气象装置核心', 0},
    ['2862C5AFC2E837BA'] = {'building', '任务交互物', 0},
    ['29D0A1DFB5FD811F'] = {'building', '任务交互物', 0},
    ['2B581BBB45DA1225'] = {'building', '燃料提取终端', 0},
    ['2B5D3186EE3A4A84'] = {'building', '变异虫卵', 555942570},
    ['2D3BC1683A54298D'] = {'building', '情报包裹', 3717706265},
    ['317B2C0E4D10E293'] = {'building', '炮塔控制数据交付点', 0},
    ['319388D1D8ACB8F3'] = {'building', 'TCS 任务终端', 0},
    ['3231BD912357A9E1'] = {'building', '任务终端', 0},
    ['33F2BCDAE3A12592'] = {'building', '超级固态硬盘', 714952129},
    ['346C42FD9C915904'] = {'building', '轨道炮终端', 0},
    ['36C5E772F8A3B9D3'] = {'building', '超级固态硬盘', 714952129},
    ['36CC8EAD2BB18D78'] = {'building', '虫穴', 3277626454},
    ['372481E910C05A76'] = {'building', '战术摄像机', 2071327434},
    ['37EB67CB7ACE7410'] = {'building', '能量核心站', 0},
    ['3A28A51BAA029E1A'] = {'building', '抽油任务钻机', 3477736393},
    ['3A2CEF12ED32A088'] = {'building', '虫穴', 3277626454},
    ['3CE56937E0BD28BD'] = {'building', '工厂区域大门', 0},
    ['3DE2415EA33B6897'] = {'building', '黑匣子', 4046999266},
    ['3E099DDF97ACF85F'] = {'building', '样本箱', 1332022394},
    ['3E993C23A25E6B88'] = {'building', '机器人任务数据', 714952129},
    ['3F2C34C69CFC94B2'] = {'building', '任务终端', 0},
    ['3F70E3503A3293F9'] = {'building', '鹈鹕燃料运输机', 0},
    ['3F8734AEC15B82AD'] = {'building', '鹈鹕飞船', 0},
    ['4012166966A9E6E9'] = {'building', 'SEAF 火炮弹药', 3660636186},
    ['4232EE48E2CFD24E'] = {'building', '机器人制造厂', 644365486},
    ['423FF97D57AB04F5'] = {'building', '地面全地形采集钻机', 3023900891},
    ['424036E9F7DE9A1E'] = {'building', '冷却阀门', 0},
    ['42786DC1DD1EACAD'] = {'building', '核导弹', 4280970126},
    ['43EC60F66E7E046B'] = {'building', '装有化学武器的背包', 3054644200},
    ['44748FFC63F78A72'] = {'building', '“虫窝破裂者”钻机', 1998289914},
    ['459DD5EB8C68C63F'] = {'building', '工厂区域入口', 0},
    ['460576BBDCF770D0'] = {'building', '军械库发电机', 0},
    ['46918A7483D70F3E'] = {'building', '任务交互物', 2851008997},
    ['4747668D063EEC06'] = {'building', '任务终端', 0},
    ['4776A1CF3F19A13B'] = {'building', '潜行虫巢穴', 3277626454},
    ['480445A33039CE5E'] = {'building', '虫卵群', 0},
    ['4A3E722B5A865E38'] = {'building', '黑匣子', 3346432464},
    ['4C182656063F121A'] = {'building', '控制塔数据交付点', 0},
    ['4FB8EB356AC8553E'] = {'building', '机器人制造厂', 3794527478},
    ['5158E582FBEB26BD'] = {'building', '机器人制造厂', 3794527478},
    ['516E4FA1D2AE46AE'] = {'building', '任务终端', 0},
    ['52D52230745B66A0'] = {'building', '任务终端', 0},
    ['534000F7801EA508'] = {'building', '数据收集交付点', 0},
    ['542A14BA4D755F4E'] = {'building', '雷达站终端', 0},
    ['54B66A0D35FDF785'] = {'building', '有机物提取终端', 0},
    ['5684D928C9AB00D1'] = {'building', '发射代码', 767789391},
    ['5726276FED2241B3'] = {'building', '轨道炮弹药', 2928771667},
    ['57DB57121F3E7ED2'] = {'building', '非法广播塔', 0},
    ['5852B7D2F865966C'] = {'building', '采油机', 0},
    ['5A14BF4098BF4259'] = {'building', '任务终端', 0},
    ['5CF84155E60C6E4D'] = {'building', '机械虫洞', 3277626454},
    ['60544E51EE260967'] = {'building', '光能者城市巨炮', 0},
    ['62D2C45A8B9703CC'] = {'building', '中继塔', 1549126177},
    ['646F5AEBDFF603CB'] = {'building', '黑匣子交付点', 0},
    ['68053EAE33FFA084'] = {'building', '光能者科技枢纽中枢', 0},
    ['682871578A4E98EB'] = {'building', '空军基地控制塔', 0},
    ['6838D8C197CC9C78'] = {'building', '轨道炮', 0},
    ['6845B56D77E61B9F'] = {'building', '军事通信终端', 0},
    ['688949109126ECE4'] = {'building', '机械虫洞', 3277626454},
    ['68BFAC3C8A03BB83'] = {'building', '战备干扰器终端', 0},
    ['6B7EE87FB2EC6455'] = {'building', '任务交互物', 0},
    ['6C62E2E25E084083'] = {'building', 'SEAF 火炮弹药', 0},
    ['6DB870D59730EE07'] = {'building', '中型冷却管道', 0},
    ['6DC9F65AF69783BD'] = {'building', '采油阀门', 0},
    ['6E499C5C95B019FC'] = {'building', '指挥碉堡', 245997106},
    ['6FDCD0D7F8EAF267'] = {'building', 'TCS 支柱', 0},
    ['705B0136A9A9D73A'] = {'building', '任务弹头', 3660636186},
    ['75BE82ED8592A6B3'] = {'building', '鹈鹕运输机', 0},
    ['766E7B3BDF79452F'] = {'building', '任务终端', 0},
    ['7B0F8449CA9D2DA0'] = {'building', '鹈鹕运输机', 0},
    ['7BDAA1BB44C3EE1C'] = {'building', '虫族战备干扰器', 0},
    ['7C81DE10F0023D08'] = {'building', '旗帜', 2728206271},
    ['7CA1B74B22C2EB9C'] = {'building', '任务交互物', 3660636186},
    ['7E4876D0DBF9C981'] = {'building', '中继塔终端', 0},
    ['7E4C6B45BCC45C3F'] = {'building', '虫穴', 3277626454},
    ['867FFD3B4EA22E05'] = {'building', '装配设施冷却管道', 0},
    ['888536AE851DCA05'] = {'building', '数据上传交互装置', 0},
    ['888EAAFD58C03C75'] = {'building', '任务货运车', 581608860},
    ['8901F188DB366B4B'] = {'building', '虫穴', 3277626454},
    ['8A50B60B22186B9B'] = {'building', '巢穴世界采油阀门', 0},
    ['8AD7A3118BD48D1C'] = {'building', '黑匣子', 4046999266},
    ['8C31B749759CBD61'] = {'building', '虫穴', 3277626454},
    ['8F7D4D9C196018C8'] = {'building', '旗帜', 2728206271},
    ['90001FEAC563D6A1'] = {'building', '公文包', 4194145910},
    ['91209E5AF7A9660B'] = {'building', '有机物提取软管接口', 0},
    ['913B7D337E61EE4C'] = {'building', '生物处理器终端', 0},
    ['925158186B8FD952'] = {'building', '中继塔对准开关', 0},
    ['95D717E4AA9ED443'] = {'building', '光能者城市巨炮曲柄', 0},
    ['973A2984F0CA6A30'] = {'building', '机器人通信终端', 0},
    ['97DD3178E9F0AB70'] = {'building', '虫穴', 3277626454},
    ['9A0D640BF4ABB03B'] = {'building', '任务终端', 0},
    ['9A1F728716DA05B5'] = {'building', '超级地球旗杆', 0},
    ['9A6A60CF4BAD9FA5'] = {'building', '防御任务终端', 0},
    ['9B58C95349D051F9'] = {'building', '虫穴', 3277626454},
    ['9B75A86003C2A1F4'] = {'building', '采油任务终端', 0},
    ['9BFC8FCD68B09F28'] = {'building', 'SEAF 火炮', 0},
    ['9D3A7E11095E3355'] = {'building', '任务旗帜', 2728206271},
    ['9D8632A79C2D9789'] = {'building', '虫穴', 3277626454},
    ['9E0E5E86A44C62A1'] = {'building', '机器人任务数据', 714952129},
    ['9EA89CEEA6F8E766'] = {'building', '幼虫储存器', 1492050893},
    ['A09A19371FECD6A3'] = {'building', 'TCS 任务终端', 0},
    ['A0EA22BD370D4D72'] = {'building', '平民撤离门', 0},
    ['A1A7B76B29088843'] = {'building', '机器人制造厂', 3794527478},
    ['A1BDB3A13E3633DD'] = {'building', 'SEAF 防空导弹阵地', 1563965062},
    ['A1E90D748B3D8AAA'] = {'building', '任务终端', 0},
    ['A21F08920052C27E'] = {'building', '发电站', 0},
    ['A3D5F183F8A2B768'] = {'building', 'SEAF 火炮装填架', 0},
    ['A531053415EB57DA'] = {'building', '任务终端', 0},
    ['A7381B87F3A3B455'] = {'building', '超级固态硬盘', 714952129},
    ['A8AE6952B375EF6C'] = {'building', '武装运输舰制造厂', 3794527478},
    ['A8B999A49716BF41'] = {'building', '光能者传送门', 0},
    ['AA28CAF964D05500'] = {'building', '孢子喷涌体', 3139947901},
    ['AC6E5FA7DB7FE621'] = {'building', '任务终端', 0},
    ['ACC611541CD839DB'] = {'building', '撤离信标', 0},
    ['AEAEF7A1851E6C9D'] = {'building', '机器人防空炮阵地', 4042981686},
    ['AFC719AF96F10DC3'] = {'building', '受感染高塔', 3896690221},
    ['B127552416CE512E'] = {'building', '任务交互物', 0},
    ['B19C942FFD41C4A5'] = {'building', '防御任务发射井', 0},
    ['B1D938C07E30C5DB'] = {'building', '洲际导弹发射井', 0},
    ['B27FE88BC708A680'] = {'building', '任务终端', 0},
    ['B31073E494A0643A'] = {'building', '含水层钻机', 1436471677},
    ['B44F8D33E16202FB'] = {'building', '精炼厂终端', 0},
    ['B50DBC63A02C0D3B'] = {'building', '任务交互物', 0},
    ['B663751EB459D242'] = {'building', '光能者古物', 3335887011},
    ['B6A181ADCF547AEB'] = {'building', '虫穴', 3277626454},
    ['B6FE4BD12C248286'] = {'building', '装配设施夹具', 0},
    ['B7C9C0D0C39AA349'] = {'building', '黑匣子回收终端', 0},
    ['B8A49F22D83D52CF'] = {'building', '洲际导弹发射井锁', 0},
    ['BA80E8D1331D8489'] = {'building', '电力恢复终端', 0},
    ['BADBA9174CAEE9FF'] = {'building', '洲际导弹发射终端', 0},
    ['BAF9DBD86B22270A'] = {'building', '统御舰', 4134104203},
    ['BB2570AFA4C767D8'] = {'building', '数据上传交付点', 0},
    ['BB2984B9B83EBFD1'] = {'building', '光能者收割设施', 0},
    ['BC2AF8548C6D5E06'] = {'building', '虫穴', 3277626454},
    ['BD20741E0225BD33'] = {'building', '有机装配设施终端', 0},
    ['BF908A82B8E787AC'] = {'building', 'TCS 支撑建筑', 0},
    ['C02C2623B6359BB3'] = {'building', '任务交互物', 0},
    ['C066DCFAA61E740C'] = {'building', '数据收集终端', 0},
    ['C2F0CC038E724374'] = {'building', 'SEAF 火炮终端', 0},
    ['C3D9B291BD97B935'] = {'building', 'TCS 支撑建筑', 0},
    ['C71C0C7B2E688B9B'] = {'building', '机密数据', 3839214628},
    ['C8F9A2233048B836'] = {'building', '任务交互物', 354671336},
    ['CB036409F28330E7'] = {'building', '任务终端', 0},
    ['D0444F56A7D86E2B'] = {'building', '发电机', 0},
    ['D3CEB59066593FBD'] = {'building', '工厂任务终端', 0},
    ['D4A349DAAE850283'] = {'building', '光能者城市巨炮锁', 0},
    ['D564F4E9E3A98599'] = {'building', '燃料补给终端', 0},
    ['D666AA61D804D311'] = {'building', '虫穴', 3277626454},
    ['D6A1019CF530FA1D'] = {'building', '中继塔控制终端', 0},
    ['D84FFC32A6E640A8'] = {'building', '机器人运输舰', 1485224906},
    ['D86B3F92DD4AAEDC'] = {'building', '平民撤离主终端', 0},
    ['D88547FF02B212E8'] = {'building', '机器人工厂', 0},
    ['D888E2EC286A4B0D'] = {'building', '任务终端', 0},
    ['D8A28BFB827392BE'] = {'building', '聚变电池', 280534572},
    ['DB59777F0ABAF6AF'] = {'building', '任务货运集装箱', 0},
    ['DC19126D15692D04'] = {'building', '任务交互物', 0},
    ['DC901B71A3A73B9A'] = {'building', '孢肺', 989829386},
    ['DEF983C174B8E083'] = {'building', '巢穴世界燃料提取终端', 0},
    ['DF3C4F91E298BFA4'] = {'building', '任务钻机', 1998289914},
    ['DF657367D712CD8E'] = {'building', '洲际导弹发射井', 0},
    ['DFA99372CEFBF84D'] = {'building', '任务终端', 0},
    ['E02E6BD34B606A85'] = {'building', '孢子喷涌体', 3139947901},
    ['E05784031312C43F'] = {'building', '巢穴世界燃料提取阀门', 0},
    ['E09FCB5A280ACB1D'] = {'building', '任务交互物', 0},
    ['E2E6E77DCC99A1CB'] = {'building', '生物处理器', 0},
    ['E41334ADBEAF0D12'] = {'building', '雷达任务终端', 0},
    ['E48C901A7175F638'] = {'building', '科研站数据上传设施', 0},
    ['E4BE3FDF0C857B7F'] = {'building', '任务交互物', 0},
    ['E73F6B5A100B7230'] = {'building', '移动雷达', 0},
    ['E98D623E013A113B'] = {'building', '任务交互物', 0},
    ['E9929CB8800E1C8F'] = {'building', '巢穴世界管道疏通阀门', 0},
    ['EAE962D85C0C2D4A'] = {'building', '抽油任务钻机', 3477736393},
    ['EECB5C13AE48637B'] = {'building', '数据上传主终端', 0},
    ['EF3A4136B21592CB'] = {'building', '鹈鹕飞船', 0},
    ['F08AE61266335A40'] = {'building', '非法科研站', 0},
    ['F0B98FB953B13960'] = {'building', '机器人制造厂', 3794527478},
    ['F1ADE19F87015997'] = {'building', '任务终端', 0},
    ['F1C4856CC0EAF603'] = {'building', '防空导弹发射终端', 0},
    ['F41432892465C5FD'] = {'building', '超级固态硬盘', 714952129},
    ['F45D1A033E848901'] = {'building', '大型冷却管道', 0},
    ['F598598C47617605'] = {'building', '任务交互物', 0},
    ['F78BF0FF5C62140D'] = {'building', '虫穴', 3277626454},
    ['F8E53685C00D926A'] = {'building', '任务交付点', 0},
    ['FB0AF9C18AAEFEF2'] = {'building', '坠毁的收割者', 0},
    ['FBD932EAC8E28E0B'] = {'building', '主发电站', 0},
    ['FF5CC825B9571052'] = {'building', '机器人迫击炮阵地', 2649067399},
    ['FF660C3FD24531A0'] = {'building', '燃料提取软管接口', 0},
}
-- END MISSION TARGET CATALOG

-- BEGIN ENEMY TARGET CATALOG
-- Generated offline by tools/generate_enemy_catalog.py from docs/enemy-catalog.json.
-- Game 1.007.100, 2026-09-22; hostile + Spottable only; flight before size.
local ENEMY_TARGETS = {
    ['0002BA767DF856F3'] = {'small_enemy', '劫掠者', 2454424572},
    ['0883366204E1CCC5'] = {'medium_enemy', '凝视者', 1661895142},
    ['089833D2880D9E06'] = {'small_enemy', '机枪奇袭者（炽灼部队）', 586021653},
    ['08E6FFC2474287BD'] = {'medium_enemy', '监视者 MK2', 3363066353},
    ['09DFB04B2E578BC3'] = {'small_enemy', '激光装甲兵', 4039692928},
    ['09FE0BE51A23396C'] = {'medium_enemy', '惑乱者（女）', 1371180916},
    ['0AB7B92B131C228C'] = {'large_enemy', '爆裂强袭虫', 3903153972},
    ['0ADC9F9173AD8E1D'] = {'small_enemy', '无票者（中型）', 4211847317},
    ['10081ACEF6163EF6'] = {'medium_enemy', '酸液武斗虫', 3365898186},
    ['137988CEA16458F7'] = {'large_enemy', '巨型碾压者', 613980508},
    ['1448D494665D01A0'] = {'small_enemy', '凝视者 MK2', 2259733865},
    ['1897BDD32105D2DC'] = {'large_enemy', '巨型炙焰者 MK2（炽灼部队）', 1775662925},
    ['19E18B46EC55D94A'] = {'flying_enemy', '刺魟', 4160806915},
    ['1A7FCDFF98C664B0'] = {'large_enemy', '强袭虫', 1299714559},
    ['1B5B9AC4F96B36E5'] = {'small_enemy', '机械统帅（炽灼部队）', 621159586},
    ['1E66EE1F6F7FD00E'] = {'large_enemy', '巨型抹煞者', 1560770730},
    ['1F0A91729C0004E0'] = {'small_enemy', '孢裂追猎虫', 1210082392},
    ['20B9C7734DAEAD65'] = {'large_enemy', '证真者', 3776682558},
    ['215CE160A17BE4CD'] = {'small_enemy', '喷气机械统帅', 621159586},
    ['257D805CAA7E10C0'] = {'small_enemy', '装甲兵 霰弹（废案）', 4039692928},
    ['262351741C53FF0C'] = {'small_enemy', '凝视者 尖塔', 2259733865},
    ['282EB766C1FFA6A1'] = {'flying_enemy', '炮艇', 1932062202},
    ['2A12104F2853AE16'] = {'small_enemy', '火箭奇袭者', 3112705780},
    ['2AD2E055DAD21F6E'] = {'flying_enemy', '入侵的穿梭舰', 3579113113},
    ['2CF3488C4845F8BD'] = {'large_enemy', '机器人 加农炮塔', 478200978},
    ['30CF04B2EC8C9BD4'] = {'small_enemy', '侦察奇袭者', 2319746535},
    ['30F2DEE2333F227A'] = {'giant_enemy', '移动工厂 带干扰塔', 1153658728},
    ['31BAE74D2F064D8D'] = {'large_enemy', '湮灭坦克 MK2', 3455009224},
    ['32541FC4EC7C9CDC'] = {'medium_enemy', '武斗虫 MK3', 3564923972},
    ['32CDEADA234FB8DF'] = {'large_enemy', '喷气巨型碾压者', 613980508},
    ['34DFD23365472E9E'] = {'flying_enemy', '突入者', 3621116014},
    ['36AA99CCE5E60146'] = {'medium_enemy', '胆汁喷涌虫', 717622970},
    ['3AFF5FD7D5450B99'] = {'large_enemy', '巨兽级强袭虫', 1076678822},
    ['3D0E03E2D574E1CA'] = {'small_enemy', '追猎虫 MK2', 3330362068},
    ['3E0537D606438FEA'] = {'large_enemy', '巨型炙焰者', 1775662925},
    ['4019623142351CB6'] = {'small_enemy', '装甲兵 MK3', 4039692928},
    ['44458A2C52B002FB'] = {'small_enemy', '无票者（重型）', 4211847317},
    ['453FE22C634EB30F'] = {'large_enemy', '御门者', 1870840792},
    ['4E97FB073BDC7A4B'] = {'medium_enemy', '武斗虫 MK2（俘虏）', 3564923972},
    ['51EEA86BF6997E4E'] = {'small_enemy', '食腐虫 MK2', 4212839382},
    ['52018DEB9AB6827E'] = {'small_enemy', '喷气装甲兵（崩溃）', 4039692928},
    ['53D8919D7B8ABD67'] = {'large_enemy', '湮灭坦克', 3455009224},
    ['54E107DACF6929CB'] = {'medium_enemy', '狂暴者 MK2', 3201222154},
    ['57EED0EAC346CD9D'] = {'medium_enemy', '蹂躏者 MK3（炽灼部队）', 1649987991},
    ['58B2B86C11369241'] = {'medium_enemy', '燃烧机枪蹂躏者', 75849082},
    ['5CA832447445C0BA'] = {'small_enemy', '追猎虫 MK3', 3330362068},
    ['6021E22338333D88'] = {'medium_enemy', '抚育喷涌虫', 487985459},
    ['604A794EC45BB820'] = {'flying_enemy', '崇高监视者', 2745056259},
    ['611BA777783B08A2'] = {'large_enemy', '噪轰引擎 速射加农炮', 4066406510},
    ['63DF3D07B7424588'] = {'large_enemy', '铁幕坦克', 3921592399},
    ['64090088502435DD'] = {'flying_enemy', '尖啸虫', 793026793},
    ['64BA5F030B114EC1'] = {'small_enemy', '奇袭者', 2000862158},
    ['672F7DA17F3BA34A'] = {'small_enemy', '穿刺虫触手', 1046000873},
    ['67DC32DCA4F02D33'] = {'large_enemy', '肉瘤体', 2880434041},
    ['6B202392F4AB605E'] = {'large_enemy', '孢子强袭虫', 1939105083},
    ['6DAB2EADF5D8B692'] = {'large_enemy', '巨型烈焰轰炸者', 2090691137},
    ['728421351D440EBC'] = {'medium_enemy', '孢裂武斗虫', 2115960485},
    ['72A83E49CED6DB3D'] = {'small_enemy', '胆汁吐沫虫', 444529084},
    ['746A7F3BEDA32699'] = {'medium_enemy', '激进先锋（男）', 23741406},
    ['74E2285C01DA4F71'] = {'flying_enemy', '增援穿梭舰', 3579113113},
    ['78E1497571012C47'] = {'small_enemy', '无票者（轻型）', 4211847317},
    ['7B48CACDBACB3881'] = {'small_enemy', '装甲兵 MK2', 4039692928},
    ['7ECE5304F868F6B3'] = {'small_enemy', '装甲兵（无包裹）', 4039692928},
    ['82A87AD8D595B2BA'] = {'small_enemy', '炙焰装甲兵', 2861014363},
    ['843D18D4B5512B63'] = {'large_enemy', '移动工厂 连发加农炮', 478200978},
    ['856E9710E45E760F'] = {'small_enemy', '特攻奇袭者', 1467464627},
    ['883401AF2A98A5F6'] = {'small_enemy', '掠食追猎虫', 3029738043},
    ['8FF0A839830A7692'] = {'small_enemy', '食腐虫', 4212839382},
    ['905809A4C28D8A45'] = {'large_enemy', '粉碎者', 3922421925},
    ['9076EEED17FCEE35'] = {'large_enemy', '强化侦察纵步者', 1871700431},
    ['91EBD77931110AFC'] = {'medium_enemy', '重型蹂躏者 MK3', 1649987991},
    ['960B48A421A3FAAA'] = {'flying_enemy', '蟑龙', 1378841226},
    ['96110F9D6B010E02'] = {'large_enemy', '敌方单位', 478200978},
    ['9647B00CC3A9D36F'] = {'medium_enemy', '火箭蹂躏者', 2365630221},
    ['965EAE5A51ACDD4A'] = {'large_enemy', '猎杀器', 1405979473},
    ['96BA14C9EBB49CE1'] = {'large_enemy', '巨型者', 790541304},
    ['98152772A72F7838'] = {'flying_enemy', '运输船', 554367013},
    ['9926876B2375A1BB'] = {'medium_enemy', '机器人 碉堡炮塔', 3921936527},
    ['9A8A3AAE287B230C'] = {'small_enemy', '食腐虫 MK3', 4212839382},
    ['9D8827FED763650E'] = {'medium_enemy', '惑乱者（男）', 1371180916},
    ['9E2E17F2CCCCAFDD'] = {'giant_enemy', '吐酸泰坦', 2514244534},
    ['9F57782F00E6ED20'] = {'small_enemy', '装甲兵（炽灼部队）', 4039692928},
    ['A05BD1EC67B3AC4C'] = {'large_enemy', '巨兽级强袭虫 MK2', 1076678822},
    ['A1F37BF2A40FBDE4'] = {'medium_enemy', '虫窝护卫', 626718113},
    ['A35207C6F2150806'] = {'medium_enemy', '爆裂武斗虫', 953392591},
    ['A381A11C07D3EB94'] = {'medium_enemy', '爆裂喷涌虫', 2270698456},
    ['A4552F97033392F4'] = {'small_enemy', '喷气机枪奇袭者', 586021653},
    ['A6A68D8AF177F3A1'] = {'medium_enemy', '狂暴者', 3201222154},
    ['A71AAFD82C6EBC92'] = {'small_enemy', '机械统帅', 621159586},
    ['AAB438596F5E8FD9'] = {'small_enemy', '猛扑虫', 908216632},
    ['ABDB2E2A0479D8CA'] = {'large_enemy', '机器人 加农炮塔 MK2', 478200978},
    ['AC60E78435098C9D'] = {'flying_enemy', '守望者', 886803190},
    ['AE57FCDB49F74E98'] = {'small_enemy', '装甲兵 MK2（机枪版）', 4039692928},
    ['AE63E525853D7044'] = {'medium_enemy', '蹂躏者 MK3', 1649987991},
    ['AF0F9B3A163787A5'] = {'small_enemy', '喷气装甲兵', 4039692928},
    ['B056F8FC74ABA02D'] = {'small_enemy', '激光炮装甲兵（废案）', 4039692928},
    ['B2A6FA1E4284C7E6'] = {'medium_enemy', '狂暴武斗虫', 3564923972},
    ['B4ED319B39F5457B'] = {'small_enemy', '机枪奇袭者', 586021653},
    ['B5DBC0C240C921AD'] = {'medium_enemy', '狂暴者 MK3（炽灼部队）', 3201222154},
    ['B92435FBF60F0748'] = {'medium_enemy', '重型蹂躏者 MK2', 398976798},
    ['BC242702FB46B7E7'] = {'large_enemy', '噪轰引擎', 4066406510},
    ['BE39E313A1E46BB9'] = {'medium_enemy', '武斗虫 MK2', 3564923972},
    ['BE743B2FAA3A6E26'] = {'medium_enemy', '喷气蹂躏者', 1649987991},
    ['C626D2BB495A202D'] = {'medium_enemy', '蹂躏者', 1649987991},
    ['C6449FFD9EA3779C'] = {'large_enemy', '碎裂坦克', 2577770154},
    ['C9BCCCB0A54A82A4'] = {'medium_enemy', '火箭蹂躏者 MK3 （炽灼部队）', 2365630221},
    ['CBB1BA3366009C3A'] = {'medium_enemy', '激进先锋（女）', 23741406},
    ['CC188F0C80505C6C'] = {'medium_enemy', '悲怜体', 2118086817},
    ['CC7022FDD172089B'] = {'medium_enemy', '抚育喷涌虫 MK2', 487985459},
    ['CCAE5264ACD591B7'] = {'medium_enemy', '胆汁喷涌虫 MK2', 717622970},
    ['CD28A27A79BE53D5'] = {'medium_enemy', '指挥碉堡 碉堡重机枪', 3921936527},
    ['D1E990BAF22D5A52'] = {'large_enemy', '掠食追踪虫', 4106686024},
    ['D37E8D120D2836E3'] = {'giant_enemy', '移动工厂', 1153658728},
    ['D465D9C7F77A07CB'] = {'giant_enemy', '霸王虫', 3929716830},
    ['D522FD4748D443A5'] = {'large_enemy', '虫族指挥官', 3077749065},
    ['D5792F6856B06BA4'] = {'medium_enemy', '喷气狂暴者', 3201222154},
    ['D63FCBFF0851B7AF'] = {'large_enemy', '猎杀器 MK2', 1405979473},
    ['D8CBC4A807A6D035'] = {'small_enemy', '乱斗者', 1974334302},
    ['D9511E9F6BD62E3F'] = {'small_enemy', '追猎虫', 3330362068},
    ['DA40BB347C7447F2'] = {'medium_enemy', '监视者', 1899936906},
    ['DB90077E76FAA025'] = {'flying_enemy', '敌方单位', 554367013},
    ['DB964631BE1CF501'] = {'small_enemy', '孢裂食腐虫', 2842755544},
    ['DCF8E74212FBEE3B'] = {'large_enemy', '穿刺虫', 1046000873},
    ['DFBACBD977A948DC'] = {'small_enemy', '食腐虫 MK2（俘虏）', 4212839382},
    ['E0353177F1329573'] = {'medium_enemy', '烈火蹂躏者', 3498181594},
    ['E44EC9F9B3FE1D2A'] = {'large_enemy', '喷气巨型炙焰者', 1775662925},
    ['E683D2CA5618D74A'] = {'small_enemy', '奇袭者（炽灼部队）', 2000862158},
    ['E8F19A0AA958E46D'] = {'medium_enemy', '新月监视者', 3877563222},
    ['EACEE39FA017B495'] = {'medium_enemy', '武斗虫', 3564923972},
    ['EF04CB84D097A497'] = {'giant_enemy', '孢裂泰坦', 2514244534},
    ['EF570293245A17C2'] = {'large_enemy', '战争纵步者', 523260929},
    ['F0B26FA9258128D3'] = {'flying_enemy', '敌方单位', 793026793},
    ['F1610AC48CDC5240'] = {'medium_enemy', '监视者（无包裹模型）', 1899936906},
    ['F22D027B37BEF107'] = {'giant_enemy', '利维坦', 3097344451},
    ['F540CA9D9D4A422E'] = {'large_enemy', '追踪虫', 2387277009},
    ['F66D0BAD8693779A'] = {'medium_enemy', '火箭蹂躏者 MK2', 2365630221},
    ['F79CD8BB654397DF'] = {'large_enemy', '阿尔法指挥官', 570845236},
    ['F8131632AA867107'] = {'large_enemy', '侦察纵步者', 20706814},
    ['F8B5A81A86D5D4EB'] = {'medium_enemy', '重型蹂躏者', 398976798},
    ['FB9937035D652C43'] = {'small_enemy', '装甲兵', 4039692928},
    ['FC8DEC78BE8AB47D'] = {'medium_enemy', '蹂躏者 MK2 移动工厂生产', 1649987991},
    ['FD5247653C897803'] = {'large_enemy', '敌方单位', 1076678822},
}
-- END ENEMY TARGET CATALOG

local PING_TARGETS = {
    -- Current EntityComponentMap Spottable identities, cross-checked with
    -- FileDiver ammo_rack/{ammo_rack,supply_box,ammo_box} and frv_supply paths.
    ['5052EC6A928CCF1A'] = {'stratagem', '重新补给'},
    ['A94913CA014F7579'] = {'stratagem', '重新补给箱'},
    ['49119612EB284A48'] = {'stratagem', '重新补给箱'},
    ['9B2140378640432E'] = {'stratagem', 'M-103 补给车'},
    ['6CFCC7F8801A0266'] = {'stratagem', "40-K Meltagun"},
    ['A8CFFB316F0B5C5F'] = {'stratagem', "AC-8 Autocannon"},
    ['89C5493E08CA4207'] = {'stratagem', "APW-1 Anti-Materiel Rifle"},
    ['96DE9CD50F7306E6'] = {'stratagem', "ARC-3 Arc Thrower"},
    ['78A8185F63A70795'] = {'stratagem', "B/FLAM-80 Cremator"},
    ['9B75217D8312DD67'] = {'stratagem', "B/MD C4 Pack"},
    ['B0F1B354BA1D38D8'] = {'stratagem', "CQC-1 One True Flag"},
    ['5F3EC9BDA2BD8553'] = {'stratagem', "CQC-20 Breaching Hammer"},
    ['BF4CFD2AEABFB5A4'] = {'stratagem', "CQC-9 Defoliation Tool"},
    ['80932FA0ED6901D3'] = {'stratagem', "EAT-17 Expendable Anti-Tank"},
    ['7617642765AC38C7'] = {'stratagem', "EAT-411 Leveller"},
    ['B2B5E0D185605F9E'] = {'stratagem', "EAT-700 Expendable Napalm"},
    ['25AA2FD4643CF4EE'] = {'stratagem', "FAF-14 Spear"},
    ['39AB99895147A3BF'] = {'stratagem', "FLAM-40 Flamethrower"},
    ['02EECD0B1FA49630'] = {'stratagem', "GL-21 Grenade Launcher"},
    ['88C2D09AD85A7C9F'] = {'stratagem', "GL-28 Belt-Fed Grenade Launcher"},
    ['FE3B29B2CFA63F9B'] = {'stratagem', "GL-52 De-Escalator"},
    ['9F80D67A12A7E40F'] = {'stratagem', "GR-8 Recoilless Rifle"},
    ['D54B9505C0F72873'] = {'stratagem', "LAS-98 激光大炮"},
    ['35A61296619CC47E'] = {'stratagem', "LAS-99 Quasar Cannon"},
    ['43A58CB89CFA197C'] = {'stratagem', "M-1000 Maxigun"},
    ['A6A735ACCB4A327F'] = {'stratagem', "M-105 Stalwart"},
    ['2152D5147B0AC418'] = {'stratagem', "MG-206 Heavy Machine Gun"},
    ['11C27D3BABB38956'] = {'stratagem', "MG-43 Machine Gun"},
    ['B16C9D490AA59B77'] = {'stratagem', "MGX-42 Bullet Storm"},
    ['5990123D142B16CB'] = {'stratagem', "MLS-4X Commando"},
    ['DE18775FA447A9BF'] = {'stratagem', "MS-11 Solo Silo"},
    ['E8D5F49AD7780E54'] = {'stratagem', "PLAS-45 Epoch"},
    ['26E40437EA275296'] = {'stratagem', "RL-77 Airburst Rocket Launcher"},
    ['2E9D0BDC48B09E60'] = {'stratagem', "RS-422 Railgun"},
    ['3828E2051AA9E897'] = {'stratagem', "S-11 Speargun"},
    ['52071F49263415E4'] = {'stratagem', "SG-88 Break-Action Shotgun"},
    ['CC786F6491FE7E65'] = {'stratagem', "StA-X3 W.A.S.P. Launcher"},
    ['88F61AFFF48AC8A4'] = {'stratagem', "TX-41 Sterilizer"},
    ['FDE262593307CA2F'] = {'stratagem', "LAS-98 激光大炮装备架"},
    ['16474112801385B6'] = {'stratagem', "堡垒坦克"},
}

-- Current DLL receiver falls back to 330A0E0[kind] for unnamed markers.
-- Read-only verification: 3585962803=location, 689074879=enemy unit;
-- Encyclopedia's common terminal key is 4234884333. Specific keys stay intact.
local GENERIC_MISSION_NAMES = {[3585962803]=true, [689074879]=true, [4234884333]=true}
-- Current data confirms these are ObjectiveShell entities, but not their shell
-- variant. Never turn their generic catalogue fallback into a claimed type.
local function build_ping_events(env)
    local ffi = require('ffi')
    local classification = {
        supply_targets = {
            ['79CCFFD281E3F3A9'] = {name_zh='弹药盒', name_en='Ammo box'},
            ['B4CA4C5B922F7965'] = {name_zh='针剂盒', name_en='Stim box'},
            ['97AF34FBF093409C'] = {name_zh='手雷包', name_en='Grenade pack'},
        },
        ambiguous_shells = {['6C62E2E25E084083']=true, ['C8F9A2233048B836']=true},
        generic_native_names = {['特殊地点']=true, ['special location']=true,
            ['敌方单位']=true, ['enemy unit']=true, ['任务交互物']=true, ['objective terminal']=true,
            ['普通物资']=true, ['supplies']=true},
        exact_supply_names = {
            ['弹药']=true, ['弹药盒']=true, ['针剂']=true, ['针剂盒']=true,
            ['手雷']=true, ['手雷包']=true, ['手雷盒']=true,
            ['样本']=true, ['样本瓶']=true, ['普通样本']=true, ['稀有样本']=true, ['超级样本']=true,
            ['普通样本瓶']=true, ['稀有样本瓶']=true, ['超级样本瓶']=true,
            ['ammo']=true, ['ammunition']=true, ['ammo box']=true, ['ammo canister']=true,
            ['stim']=true, ['stims']=true, ['stim box']=true, ['stim case']=true,
            ['grenade']=true, ['grenades']=true, ['grenade box']=true, ['grenade case']=true,
            ['grenade pack']=true, ['sample']=true, ['samples']=true, ['common sample']=true,
            ['rare sample']=true, ['super sample']=true, ['sample vial']=true,
        },
    }
    local state = {scene = nil, seen = {}, generation = 0, serial = 0, status = '等待标记数据'}
    local api = {state = state, supported = {small_enemy = true, flying_enemy = true,
        medium_enemy = true, large_enemy = true,
        giant_enemy = true, building = true, supplies = true, stratagem = true, map = true}}
    local function selected_name(row)
        local language
        if env.language then
            local okay, value = pcall(env.language)
            if okay then language = value end
        end
        if type(language) == 'string' and language:lower():match('^en') then
            return row.name_en or row.name_zh
        end
        return row.name_zh or row.name_en
    end
    local function report_drop(reason, entry, resource)
        if not env.diagnostic then return end
        pcall(env.diagnostic, reason, entry.kind, entry.map_type,
            entry.target_id ~= 0 and entry.target_id ~= 0xffffffff,
            entry.localization_key, resource)
    end
    local function generic_name(name, key)
        if type(name) == 'string' then
            name = name:match('^%s*(.-)%s*$')
            local lower = name:lower()
            return GENERIC_MISSION_NAMES[key]
                or classification.generic_native_names[name]
                or classification.generic_native_names[lower] or false
        end
        return GENERIC_MISSION_NAMES[key] or false
    end
    local function exact_supply_name(name)
        if type(name) ~= 'string' then return false end
        name = name:match('^%s*(.-)%s*$')
        return classification.exact_supply_names[name]
            or classification.exact_supply_names[name:lower()] or false
    end
    local function reset(reason)
        state.scene, state.session, state.seen = nil, nil, {}
        state.map_scene = nil
        state.status = reason or '等待标记数据'
    end
    function api.reset() reset() end
    local function u32(bytes, at)
        local a,b,c,d = bytes:byte(at + 1, at + 4)
        assert(d, 'short integer read')
        return a + b*256 + c*65536 + d*16777216
    end
    local function hex64(bytes, at)
        return string.format('%08X%08X', u32(bytes, at + 4), u32(bytes, at))
    end
    local function float(bytes, at)
        local value = ffi.new('uint32_t[1]', u32(bytes, at))
        return tonumber(ffi.cast('float *', value)[0])
    end
    local function mul32(a, b)
        local al,bl = a%65536,b%65536
        return (al*bl + ((math.floor(a/65536)*bl + math.floor(b/65536)*al)%65536)*65536)%4294967296
    end

    local function observe(base)
        local session = env.session and env.session() or false
        assert(not env.session or session ~= false and session ~= nil, 'ping session unavailable')
        local calls, mapping_guards = 0, {}
        local function read(address, n)
            assert(type(address) == 'number' and address%1 == 0 and address >= 65536
                and n > 0 and n <= 65536 and address+n < 2^47, 'invalid ping read bounds')
            calls = calls + 1; assert(calls <= 2048, 'ping read budget exceeded')
            local bytes = env.read(address, n)
            assert(type(bytes) == 'string' and #bytes == n, 'ping data unreadable')
            return bytes
        end
        local function ptr(address)
            local bytes = read(address, 8)
            local value = u32(bytes, 0) + u32(bytes, 4)*4294967296
            assert(value >= 65536 and value%8 == 0 and value < 2^47, 'invalid ping pointer')
            return value
        end
        local function word(address) return u32(read(address, 4), 0) end
        local function guarded(address, n)
            local bytes = read(address, n)
            mapping_guards[#mapping_guards+1] = {address, bytes}
            return bytes
        end
        local function guarded_ptr(address)
            local bytes = guarded(address,8)
            local value = u32(bytes,0)+u32(bytes,4)*4294967296
            assert(value >= 65536 and value%8 == 0 and value < 2^47, 'invalid guarded pointer')
            return value
        end
        local function lookup(address, key, limit)
            local header = guarded(address, 20)
            local slots = u32(header, 0) + u32(header, 4)*4294967296
            local cap, empty, factor = u32(header, 8), u32(header, 12), u32(header, 16)
            assert(slots >= 65536 and slots%4 == 0 and slots < 2^47
                and cap > 0 and cap <= 1048576, 'invalid ping entity table')
            local power = cap
            while power > 1 and power%2 == 0 do power = power/2 end
            assert(power == 1, 'invalid ping entity capacity')
            if key == empty then return nil end
            for probe = 0, math.min(cap, 256)-1 do
                local row = guarded(slots + ((mul32(key, factor)+probe)%cap)*8, 8)
                local found, index = u32(row, 0), u32(row, 4)
                if found == empty then return nil end
                if found == key then
                    if index == 0xffffffff then return nil end
                    assert(index < limit, 'invalid ping entity index')
                    return index
                end
            end
            error('ping entity lookup exhausted')
        end
        local ctx, root, players, ring = ptr(base+0x347cef0), ptr(base+0x346bf98),
            ptr(base+0x3326468), ptr(base+0x347ce30)
        if env.context then assert(env.context() == ctx, 'ping network context changed') end
        local own_bytes = read(ctx+0xb398, 8)
        local own = hex64(own_bytes, 0)
        assert(own ~= '0000000000000000', 'local ping peer unavailable')
        local count = word(players+0x84)
        assert(count > 0 and count <= 4, 'invalid ping player count')
        local creators, own_present, roster_guards = {}, false, {}
        local function owned_entity(entity, peer)
            if entity == nil or entity == 0 or entity == 0xffffffff then return end
            -- Ambiguous/recycled player bindings cannot attribute an event.
            if creators[entity] and creators[entity] ~= peer then creators[entity] = false
            elseif creators[entity] == nil then creators[entity] = peer end
        end
        for slot = 0, count-1 do
            local peer_at = players+0x2c8+slot*0x38
            local peer_bytes = read(peer_at, 8)
            local peer = hex64(peer_bytes, 0)
            roster_guards[#roster_guards+1] = {peer_at, peer_bytes}
            if peer ~= '0000000000000000' then
                if peer == own then own_present = true end
                local descriptor_at = players+0xe8+slot*8
                local descriptor_bytes = guarded(descriptor_at, 8)
                local descriptor = u32(descriptor_bytes, 0)+u32(descriptor_bytes, 4)*4294967296
                assert(descriptor >= 65536 and descriptor%8 == 0 and descriptor < 2^47, 'invalid player descriptor')
                local player_entity = read(descriptor+8, 4)
                owned_entity(u32(player_entity, 0), peer)
                roster_guards[#roster_guards+1] = {descriptor+8, player_entity}
                local network_at = players+0x3a8+slot*0x20
                local network_bytes = read(network_at, 4)
                roster_guards[#roster_guards+1] = {network_at, network_bytes}
                local network = u32(network_bytes, 0)
                if network < 0x7fff then
                    local index = lookup(root+0xf22ec8, network, 2048)
                    if index then
                        local identity_at = root+0xf32f18+index*24
                        local identity = read(identity_at, 24)
                        assert(u32(identity, 16) == network, 'ping avatar network identity changed')
                        owned_entity(u32(identity, 8), peer)
                        roster_guards[#roster_guards+1] = {identity_at, identity}
                    end
                end
            end
        end
        assert(own_present, 'local ping peer absent from roster')
        local header = read(ring, 16)
        local head, tail = u32(header, 8), u32(header, 12)
        assert(head < 128 and tail < 128, 'invalid ping ring bounds')
        local entries, entry_guards = {}, {}
        -- Map21's receiver returns before inserting a HUD record. Read the
        -- authoritative replicated actor pins, which also include our own pin.
        local map_scene
        local have_actor_global, actor_global = pcall(read, base+0x3326d20, 8)
        if have_actor_global and hex64(actor_global, 0) ~= '0000000000000000' then
            local actors = ptr(base+0x3326d20)
            mapping_guards[#mapping_guards+1] = {base+0x3326d20, actor_global}
            local actor_count = u32(guarded(actors+0x6c, 4), 0)
            assert(actor_count <= 16, 'invalid map actor count')
            map_scene = string.format('%X', actors)
            for slot = 0, actor_count-1 do
                local descriptor_bytes = guarded(actors+0x110+slot*8, 8)
                local descriptor = u32(descriptor_bytes,0)+u32(descriptor_bytes,4)*4294967296
                assert(descriptor >= 65536 and descriptor%8 == 0 and descriptor < 2^47, 'invalid map actor descriptor')
                local creator = u32(guarded(descriptor+8, 4), 0)
                if creators[creator] then
                    local address = actors+0x547830+slot*0x78
                    -- Guard only the mark bit and pin fields; other actor flags
                    -- can change normally while this read-only snapshot is taken.
                    local flags = read(address, 4)
                    local active = math.floor(u32(flags,0)/4)%2 == 1
                    local pin = guarded(address+0x50, 20)
                    entry_guards[#entry_guards+1] = {map_address=address, active=active}
                    if active and u32(pin,12) ~= 0 then
                        entries[#entries+1] = {slot=128+slot, age=0, kind=21,
                            creator=creator, creator_id=creators[creator], target_id=0xffffffff,
                            target_network=u32(pin,16), map_type=u32(pin,12), localization_key=0,
                            position={x=float(pin,0),y=float(pin,4),z=float(pin,8)},
                            map_source=true, token=string.format('%X:',creator)..pin}
                    end
                end
            end
        end
        assert(header:byte(1) == 1 or map_scene, 'ping UI inactive')
        local function token(bytes)
            return bytes:sub(1,4)..bytes:sub(17,20)..bytes:sub(25,28)..bytes:sub(33,36)
                .. bytes:sub(53,56)
                .. string.char(math.floor(u32(bytes,0x1c)/0x2000)%2)
                .. (u32(bytes,0)==21 and bytes:sub(5,16) or '')
        end
        for step = 0, (header:byte(1) == 1 and (tail-head)%128 or 0)-1 do
            local slot = (head+step)%128
            local bytes = read(ring+16+slot*0x58, 0x58)
            local duration, age = float(bytes, 0x10), float(bytes, 0x14)
            if (not map_scene or u32(bytes,0) ~= 21)
                and duration == duration and duration > 0 and duration <= 10000
                and age == age and age >= 0 and age < duration then
                local kind, creator, target = u32(bytes, 0), u32(bytes, 0x18), u32(bytes, 0x20)
                entries[#entries+1] = {slot = slot, age = age, kind = kind, creator = creator,
                    duration = duration, native_flags = u32(bytes,0x1c),
                    creator_id = creators[creator], target_id = target,
                    position = {x=float(bytes,4),y=float(bytes,8),z=float(bytes,12)},
                    localization_key=u32(bytes,0x34), token = token(bytes)}
                entry_guards[#entry_guards+1] = {address=ring+16+slot*0x58, token=token(bytes), age=age, duration=duration}
            end
        end
        local definitions
        local importance_kinds = {[0]='primary', [1]='prerequisite', [2]='optional', [3]='tactical'}
        local function localized_name(key)
            if key == 0 or not env.localize then return nil end
            local okay, value = pcall(env.localize, key)
            if okay and type(value) == 'string' and #value > 0 and #value <= 256 then
                value = value:gsub('[%c<>]', '')
                if value ~= '' and not value:match('^#%d+$') then return value end
            end
        end
        local function objective_name(entity)
            local manager = guarded_ptr(base+0x3326da0)
            local objective_count = u32(guarded(manager+0x24,4),0)
            assert(objective_count <= 2048, 'invalid objective count')
            local index = lookup(manager+0x38, entity, 2048)
            if not index or index >= objective_count then return nil end
            local descriptors = guarded_ptr(manager+0x50)
            local descriptor_at = descriptors+index*8
            local descriptor = guarded_ptr(descriptor_at)
            local identity = guarded(descriptor,24)
            if u32(identity,8) ~= entity then return nil end
            local runtimes = guarded_ptr(manager+0x60)
            local runtime = runtimes+index*0x1078
            local importance = u32(guarded(runtime+0x1038,4),0)
            local override = guarded(runtime+0x1054,1):byte(1)
            assert(override <= 1, 'invalid objective name override')
            local key
            if override == 1 then
                key = u32(guarded(runtime+0x1050,4),0)
            else
                definitions = definitions or read(base+0x32ef870,153*0xa0)
                for n=0,152 do
                    local at = n*0xa0
                    if definitions:sub(at+0x19,at+0x20) == identity:sub(1,8) then
                        local definition = definitions:sub(at+1,at+0xa0)
                        mapping_guards[#mapping_guards+1] = {base+0x32ef870+at,definition}
                        key = u32(definition,0x38)
                        break
                    end
                end
            end
            local name = key and localized_name(key)
            if not name then return nil end
            return {target=name, localization_key=key, objective_kind=importance_kinds[importance] or 'unknown',
                objective_importance=importance, objective_name=name}
        end
        local function target(entry)
            if entry.kind == 24 or not entry.creator_id then return nil end
            if entry.kind == 0 and (entry.target_id == 0 or entry.target_id == 0xffffffff
                or entry.target_id == entry.creator) then return nil end
            if entry.kind == 21 then
                -- Empty map pins (7) and untyped HUD records carry no useful target.
                -- Only replicated objectives (1) and extraction (6) are supported.
                if entry.map_type ~= 1 and entry.map_type ~= 6 then return nil end
                for _, value in pairs(entry.position) do
                    if value ~= value or math.abs(value)>1000000 then return nil end
                end
                local event = {category='map',target=localized_name(entry.localization_key) or '地图标记',position=entry.position,
                    creator_id=entry.creator_id,kind=entry.kind,slot=entry.slot,
                    source='tactical_map',localization_key=entry.localization_key}
                -- Captured replicated MapMarkerType 6 is the extraction pin.
                if entry.map_type == 6 then event.target = '撤离区' end
                if entry.map_type == 1 then
                    if entry.target_network >= 0x7fff then return nil,'retry' end
                    local index = lookup(root+0xf22ec8,entry.target_network,2048)
                    if not index then return nil,'retry' end
                    local identity = guarded(root+0xf32f18+index*24,24)
                    if u32(identity,16) ~= entry.target_network then return nil,'retry' end
                    local entity = u32(identity,8)
                    local objective = objective_name(entity)
                    if not objective then return nil,'retry' end
                    for key,value in pairs(objective) do event[key]=value end
                    event.target_id = entity
                    event.source = 'map_objective'
                end
                return event
            end
            -- Captured call-ins use the persistent Stratagem marker. The current
            -- receiver sets 0x2000 only after resolving the stratagem manager;
            -- neither the category nor the displayed name alone proves a summon.
            local summoned = entry.kind == 20 and entry.duration == 9999
                and math.floor(entry.native_flags/0x2000)%2 == 1
            local action = summoned and 'summon' or 'mark'
            local localized = localized_name(entry.localization_key)
            -- The game selects these through Spottable.marker_type/override. Only
            -- accept otherwise unknown resources when the native UI label resolves.
            local native_category = (entry.kind==18 or entry.kind==19) and 'building'
                or entry.kind==20 and 'stratagem' or nil
            if native_category == 'building' and (entry.target_id==0 or entry.target_id==0xffffffff)
                and exact_supply_name(localized) then
                return {category='supplies',target=localized,position=entry.position,
                    creator_id=entry.creator_id,kind=entry.kind,slot=entry.slot,
                    localization_key=entry.localization_key,action=action,source='native_marker'}
            end
            if native_category and (entry.target_id==0 or entry.target_id==0xffffffff) then
                if not localized and entry.localization_key > 0 then return nil, 'retry' end
                if not localized or generic_name(localized, entry.localization_key) then
                    report_drop('missing_target_or_generic_name', entry)
                    return nil
                end
                return {category=native_category,target=localized,position=entry.position,
                    creator_id=entry.creator_id,kind=entry.kind,slot=entry.slot,
                    localization_key=entry.localization_key,action=action,
                    source=summoned and 'stratagem_call' or 'native_marker'}
            end
            if entry.target_id == 0 or entry.target_id == 0xffffffff
                or entry.target_id == entry.creator then return nil end
            local index = lookup(root+0xf1aeb0, entry.target_id, 2048)
            if not index then return nil, 'retry' end
            local address = root+0xf32f18+index*24
            local identity = guarded(address, 24)
            if u32(identity, 8) ~= entry.target_id then return nil, 'retry' end
            local resource = hex64(identity, 0)
            local mission = MISSION_TARGETS[resource]
            if not mission and exact_supply_name(localized) then
                if read(address, 24) ~= identity then return nil, 'retry' end
                return {category='supplies',target=localized,target_id=entry.target_id,
                    creator_id=entry.creator_id,resource=resource,kind=entry.kind,slot=entry.slot,
                    localization_key=entry.localization_key,position=entry.position,action=action,
                    source=summoned and 'stratagem_call' or 'target'}
            end
            if EXCLUDED_SUPPLIES[resource] then
                local supply = classification.supply_targets[resource]
                local label = supply and selected_name(supply)
                    or (localized and not generic_name(localized, entry.localization_key) and localized)
                if not label then
                    report_drop('supply_without_specific_name', entry, resource)
                    return nil
                end
                if read(address, 24) ~= identity then return nil, 'retry' end
                return {category='supplies',target=label,target_id=entry.target_id,
                    creator_id=entry.creator_id,resource=resource,kind=entry.kind,slot=entry.slot,
                    localization_key=entry.localization_key,position=entry.position,action=action,
                    source=summoned and 'stratagem_call' or 'target'}
            end
            if classification.ambiguous_shells[resource] and (not localized
                or generic_name(localized, entry.localization_key)) then
                report_drop('ambiguous_shell_without_specific_name', entry, resource)
                return nil
            end
            -- A ground-style marker is meaningful only when its actual target
            -- identity is a reviewed task resource. Empty terrain still exits
            -- above, and arbitrary objects/enemies do not become locations.
            if entry.kind == 0 and not mission then return nil end
            local enemy = ENEMY_TARGETS[resource]
            local special = env.special_targets and env.special_targets.resolve(resource,
                entry.localization_key) or nil
            local info = mission or enemy or PING_TARGETS[resource]
            if special then
                if read(address, 24) ~= identity then return nil, 'retry' end
                local target = localized and not generic_name(localized, entry.localization_key)
                    and localized or selected_name(special)
                return {category='building',target=target,target_id=entry.target_id,
                    creator_id=entry.creator_id,resource=resource,kind=entry.kind,slot=entry.slot,
                    localization_key=entry.localization_key,position=entry.position,action=action,
                    source=summoned and 'stratagem_call' or 'target'}
            end
            if not info and (not native_category or not localized
                or generic_name(localized, entry.localization_key)) then
                report_drop('unknown_target_or_generic_name', entry, resource)
                return nil
            end
            if read(address, 24) ~= identity then return nil, 'retry' end
            local label = localized or info and info[2]
            -- Mission sites and enemies can share generic marker keys. Resolve
            -- the catalog's actual Encyclopedia name before its reviewed fallback;
            -- keep specific native marker text when it is available.
            if (mission or enemy) and (not localized or GENERIC_MISSION_NAMES[entry.localization_key]) then
                label = localized_name(info[3]) or info[2]
            end
            if info and native_category and not mission and not enemy
                and generic_name(localized, entry.localization_key) then
                label = info[2]
            end
            if info and info[2]:match('^TCS') and localized and not localized:find('TCS',1,true)
                and not GENERIC_MISSION_NAMES[entry.localization_key] then
                label = info[2] .. ' / ' .. localized
            end
            return {category = info and info[1] or native_category,
                target = label, target_id = entry.target_id,
                creator_id = entry.creator_id, resource = resource, kind = entry.kind, slot = entry.slot,
                localization_key=entry.localization_key, position=entry.position, action=action,
                source=summoned and 'stratagem_call' or 'target'}
        end
        local function validate()
            -- Recheck after target reads as well: a leaving/reordered teammate
            -- must never leave a stale attribution in the outgoing event batch.
            assert((not env.session or env.session() == session) and env.base() == base and ptr(base+0x347cef0) == ctx and ptr(base+0x346bf98) == root
                and ptr(base+0x3326468) == players and ptr(base+0x347ce30) == ring
                and read(ctx+0xb398, 8) == own_bytes and word(players+0x84) == count
                and read(ring, 16) == header, 'ping observation changed')
            for _, guard in ipairs(entry_guards) do
                if guard.map_address then
                    assert((math.floor(word(guard.map_address)/4)%2 == 1) == guard.active, 'map pin changed')
                else
                    local bytes = read(guard.address, 0x58)
                    local age = float(bytes, 0x14)
                    assert(token(bytes) == guard.token and age == age and age >= guard.age
                        and age < guard.duration, 'ping record changed')
                end
            end
            for _, guards in ipairs({roster_guards, mapping_guards}) do
                for _, guard in ipairs(guards) do
                    assert(read(guard[1], #guard[2]) == guard[2], 'ping identity mapping changed')
                end
            end
        end
        validate()
        return {base=base, session=session, scene = string.format('%X:%X:%X:%X:%X:%s', base, ctx, root, players, ring, own),
            entries = entries, map_scene=map_scene, target = target, read = read, ctx = ctx, root = root, ring = ring,
            own = own, header = header, ptr = ptr, validate = validate}
    end

    function api.poll(now)
        if type(now) ~= 'number' or now ~= now or now == math.huge or now == -math.huge then
            reset('标记计时不可用'); return 0, state.status
        end
        local okay, snapshot = pcall(function()
            local base = env.base()
            assert(type(base) == 'number' and base >= 65536 and base < 2^47, 'unverified game build')
            return observe(base)
        end)
        if not okay then reset('标记数据暂不可用'); return 0, state.status end
        local first = state.scene ~= snapshot.scene or state.session ~= snapshot.session
        local first_map = first or state.map_scene ~= snapshot.map_scene
        if first then state.generation = state.generation+1; state.seen = {} end
        local next_seen, events = {}, {}
        for _, entry in ipairs(snapshot.entries) do
            local previous = state.seen[entry.slot]
            local token_changed = not previous or previous.token ~= entry.token
            local age_reset = previous and entry.age < previous.age
            local fresh = token_changed or age_reset or previous.pending or previous.pending_emit
            next_seen[entry.slot] = {token = entry.token, age = entry.age}
            if not first and not (entry.map_source and first_map) and fresh then
                local event, reason
                local reusable = not token_changed and not age_reset and previous.pending_emit
                    and type(previous.event) == 'table'
                if reusable then
                    event = previous.event
                else
                    local good
                    good, event, reason = pcall(snapshot.target, entry)
                    if not good or reason == 'retry' then
                        -- A target can finish streaming after its ping arrives. Preserve
                        -- freshness until it resolves or the native mark expires.
                        next_seen[entry.slot] = {token=entry.token, age=entry.age, pending=true}
                        event = nil
                    end
                end
                if event then
                    if not reusable then
                        state.serial = state.serial+1
                        -- Every legitimate renewal gets a distinct key even for the same
                        -- target and slot; the caller's queue can dedupe repeated polls.
                        event.key = snapshot.scene..':'..state.generation..':'..state.serial
                        event.id = event.key
                    end
                    events[#events+1] = event
                end
            end
        end
        -- Target reads may race a world transition; discard the entire batch.
        local valid = pcall(snapshot.validate)
        if not valid then reset('标记数据切换中'); return 0, state.status end
        state.scene, state.session, state.seen = snapshot.scene, snapshot.session, next_seen
        state.map_scene = snapshot.map_scene
        local emitted = 0
        for _, event in ipairs(events) do
            -- A listener may change the room while handling the previous event.
            -- Never recapture old observations as events from the new session.
            local stable, same = pcall(function()
                return env.base() == snapshot.base
                    and (not env.session or env.session() == snapshot.session)
                    and (not env.context or env.context() == snapshot.ctx)
            end)
            if not stable or not same then
                reset('标记数据切换中'); return emitted, state.status
            end
            local success, accepted, disposition = pcall(env.emit, event, now)
            if success and accepted == true then emitted = emitted+1 end
            if success and accepted == false and disposition == 'retry' then
                local pending = state.seen[event.slot]
                if pending and pending.token then
                    state.seen[event.slot] = {token=pending.token, age=pending.age,
                        pending_emit=true, event=event}
                end
            end
        end
        state.status = first and '已记录现有标记' or emitted > 0 and '已识别玩家标记' or '等待新的玩家标记'
        return emitted, state.status
    end
    return api
end
